import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Internal Imports
import Navbar from "./ui/components/Navbar";
import Footer from "./ui/components/Footer";

// external imports
import { ChakraProvider, Flex, Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Box minHeight="100vh" display="flex" flexDirection="column">
            <Navbar />
            {children}
            <Footer />
          </Box>
        </ChakraProvider>
      </body>
    </html>
  );
}
